services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./api:/var/www/html/api"
    ports:
      - 8080:80
    restart: always
    depends_on:
      - php
      # - mysqldb

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./api:/var/www/html/api
    restart: always
    # depends_on:
      # - mysqldb

  # mysqldb:
  #   image: mysql:latest
  #   container_name: mysql
  #   volumes:
  #     - "./data/mysql:/var/lib/mysql"
  #   ports:
  #     - 3307:3306
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: recipes
  #     MYSQL_ROOT_PASSWORD: 1123581321
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass