services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src/public:/var/www/html/public"
      - "./src/app:/var/www/html/app"
    ports:
      - 8080:80
    restart: always
    depends_on:
      - php
      - mysqldb

  php:
    build: "."
    container_name: php
    volumes:
      - "./src/public:/var/www/html/public"
      - "./src/app:/var/www/html/app"
    restart: always
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    container_name: mysql
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_DATABASE: recipes_db
      MYSQL_ROOT_PASSWORD: 1123581321
      MYSQL_USER: user
      MYSQL_PASSWORD: pass